// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/flawless/terraform-provider-airbyte/internal/sdk/models/shared"
	"net/http"
)

type ListPrivateSourceDefinitionsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful operation
	PrivateSourceDefinitionReadList *shared.PrivateSourceDefinitionReadList
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ListPrivateSourceDefinitionsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListPrivateSourceDefinitionsResponse) GetPrivateSourceDefinitionReadList() *shared.PrivateSourceDefinitionReadList {
	if o == nil {
		return nil
	}
	return o.PrivateSourceDefinitionReadList
}

func (o *ListPrivateSourceDefinitionsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListPrivateSourceDefinitionsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
