// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AttemptNormalizationStatusReadList struct {
	AttemptNormalizationStatuses []AttemptNormalizationStatusRead `json:"attemptNormalizationStatuses,omitempty"`
}
