// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ConnectorBuilderPublishRequestBody struct {
	BuilderProjectID           string                    `json:"builderProjectId"`
	InitialDeclarativeManifest DeclarativeSourceManifest `json:"initialDeclarativeManifest"`
	Name                       string                    `json:"name"`
	WorkspaceID                string                    `json:"workspaceId"`
}

func (o *ConnectorBuilderPublishRequestBody) GetBuilderProjectID() string {
	if o == nil {
		return ""
	}
	return o.BuilderProjectID
}

func (o *ConnectorBuilderPublishRequestBody) GetInitialDeclarativeManifest() DeclarativeSourceManifest {
	if o == nil {
		return DeclarativeSourceManifest{}
	}
	return o.InitialDeclarativeManifest
}

func (o *ConnectorBuilderPublishRequestBody) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ConnectorBuilderPublishRequestBody) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}
