// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DeclarativeManifestsReadList struct {
	ManifestVersions []DeclarativeManifestVersionRead `json:"manifestVersions"`
}
