// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DestinationDefinitionReadList struct {
	DestinationDefinitions []DestinationDefinitionRead `json:"destinationDefinitions"`
}
