// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ExistingConnectorBuilderProjectWithWorkspaceID struct {
	BuilderProject   ConnectorBuilderProjectDetails `json:"builderProject"`
	BuilderProjectID string                         `json:"builderProjectId"`
	WorkspaceID      string                         `json:"workspaceId"`
}

func (o *ExistingConnectorBuilderProjectWithWorkspaceID) GetBuilderProject() ConnectorBuilderProjectDetails {
	if o == nil {
		return ConnectorBuilderProjectDetails{}
	}
	return o.BuilderProject
}

func (o *ExistingConnectorBuilderProjectWithWorkspaceID) GetBuilderProjectID() string {
	if o == nil {
		return ""
	}
	return o.BuilderProjectID
}

func (o *ExistingConnectorBuilderProjectWithWorkspaceID) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}
