// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type FieldSchemaUpdate struct {
	// JSONSchema representation of the field
	NewSchema FieldSchema `json:"newSchema"`
	// JSONSchema representation of the field
	OldSchema FieldSchema `json:"oldSchema"`
}

func (o *FieldSchemaUpdate) GetNewSchema() FieldSchema {
	if o == nil {
		return FieldSchema{}
	}
	return o.NewSchema
}

func (o *FieldSchemaUpdate) GetOldSchema() FieldSchema {
	if o == nil {
		return FieldSchema{}
	}
	return o.OldSchema
}
