// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type JobDebugInfoRead struct {
	Attempts      []AttemptInfoRead  `json:"attempts"`
	Job           JobDebugRead       `json:"job"`
	WorkflowState *WorkflowStateRead `json:"workflowState,omitempty"`
}
