// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type JobWithAttemptsRead struct {
	Attempts []AttemptRead `json:"attempts,omitempty"`
	Job      *JobRead      `json:"job,omitempty"`
}

func (o *JobWithAttemptsRead) GetAttempts() []AttemptRead {
	if o == nil {
		return nil
	}
	return o.Attempts
}

func (o *JobWithAttemptsRead) GetJob() *JobRead {
	if o == nil {
		return nil
	}
	return o.Job
}
