// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type NotFoundKnownExceptionInfo struct {
	ExceptionClassName          *string  `json:"exceptionClassName,omitempty"`
	ExceptionStack              []string `json:"exceptionStack,omitempty"`
	ID                          *string  `json:"id,omitempty"`
	Message                     string   `json:"message"`
	RootCauseExceptionClassName *string  `json:"rootCauseExceptionClassName,omitempty"`
	RootCauseExceptionStack     []string `json:"rootCauseExceptionStack,omitempty"`
}

func (o *NotFoundKnownExceptionInfo) GetExceptionClassName() *string {
	if o == nil {
		return nil
	}
	return o.ExceptionClassName
}

func (o *NotFoundKnownExceptionInfo) GetExceptionStack() []string {
	if o == nil {
		return nil
	}
	return o.ExceptionStack
}

func (o *NotFoundKnownExceptionInfo) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *NotFoundKnownExceptionInfo) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *NotFoundKnownExceptionInfo) GetRootCauseExceptionClassName() *string {
	if o == nil {
		return nil
	}
	return o.RootCauseExceptionClassName
}

func (o *NotFoundKnownExceptionInfo) GetRootCauseExceptionStack() []string {
	if o == nil {
		return nil
	}
	return o.RootCauseExceptionStack
}
