// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type NotificationItem struct {
	CustomerioConfiguration *CustomerioNotificationConfiguration `json:"customerioConfiguration,omitempty"`
	NotificationType        []NotificationType                   `json:"notificationType,omitempty"`
	SlackConfiguration      *SlackNotificationConfiguration      `json:"slackConfiguration,omitempty"`
}

func (o *NotificationItem) GetCustomerioConfiguration() *CustomerioNotificationConfiguration {
	if o == nil {
		return nil
	}
	return o.CustomerioConfiguration
}

func (o *NotificationItem) GetNotificationType() []NotificationType {
	if o == nil {
		return nil
	}
	return o.NotificationType
}

func (o *NotificationItem) GetSlackConfiguration() *SlackNotificationConfiguration {
	if o == nil {
		return nil
	}
	return o.SlackConfiguration
}
