// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Notification struct {
	CustomerioConfiguration *CustomerioNotificationConfiguration `json:"customerioConfiguration,omitempty"`
	NotificationType        NotificationType                     `json:"notificationType"`
	SendOnFailure           *bool                                `json:"sendOnFailure,omitempty"`
	SendOnSuccess           *bool                                `json:"sendOnSuccess,omitempty"`
	SlackConfiguration      *SlackNotificationConfiguration      `json:"slackConfiguration,omitempty"`
}
