// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OperatorDbt struct {
	DbtArguments  *string `json:"dbtArguments,omitempty"`
	DockerImage   *string `json:"dockerImage,omitempty"`
	GitRepoBranch *string `json:"gitRepoBranch,omitempty"`
	GitRepoURL    string  `json:"gitRepoUrl"`
}

func (o *OperatorDbt) GetDbtArguments() *string {
	if o == nil {
		return nil
	}
	return o.DbtArguments
}

func (o *OperatorDbt) GetDockerImage() *string {
	if o == nil {
		return nil
	}
	return o.DockerImage
}

func (o *OperatorDbt) GetGitRepoBranch() *string {
	if o == nil {
		return nil
	}
	return o.GitRepoBranch
}

func (o *OperatorDbt) GetGitRepoURL() string {
	if o == nil {
		return ""
	}
	return o.GitRepoURL
}
