// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PrivateDestinationDefinitionRead struct {
	DestinationDefinition DestinationDefinitionRead `json:"destinationDefinition"`
	Granted               bool                      `json:"granted"`
}
