// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SetInstancewideSourceOauthParamsRequestBody struct {
	Params             map[string]interface{} `json:"params"`
	SourceDefinitionID string                 `json:"sourceDefinitionId"`
}

func (o *SetInstancewideSourceOauthParamsRequestBody) GetParams() map[string]interface{} {
	if o == nil {
		return map[string]interface{}{}
	}
	return o.Params
}

func (o *SetInstancewideSourceOauthParamsRequestBody) GetSourceDefinitionID() string {
	if o == nil {
		return ""
	}
	return o.SourceDefinitionID
}
