// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SourceDefinitionSpecificationRead struct {
	AdvancedAuth *AdvancedAuth `json:"advancedAuth,omitempty"`
	// The specification for what values are required to configure the sourceDefinition.
	ConnectionSpecification *SourceDefinitionSpecification `json:"connectionSpecification,omitempty"`
	DocumentationURL        *string                        `json:"documentationUrl,omitempty"`
	JobInfo                 SynchronousJobRead             `json:"jobInfo"`
	SourceDefinitionID      string                         `json:"sourceDefinitionId"`
}

func (o *SourceDefinitionSpecificationRead) GetAdvancedAuth() *AdvancedAuth {
	if o == nil {
		return nil
	}
	return o.AdvancedAuth
}

func (o *SourceDefinitionSpecificationRead) GetConnectionSpecification() *SourceDefinitionSpecification {
	if o == nil {
		return nil
	}
	return o.ConnectionSpecification
}

func (o *SourceDefinitionSpecificationRead) GetDocumentationURL() *string {
	if o == nil {
		return nil
	}
	return o.DocumentationURL
}

func (o *SourceDefinitionSpecificationRead) GetJobInfo() SynchronousJobRead {
	if o == nil {
		return SynchronousJobRead{}
	}
	return o.JobInfo
}

func (o *SourceDefinitionSpecificationRead) GetSourceDefinitionID() string {
	if o == nil {
		return ""
	}
	return o.SourceDefinitionID
}
