// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// SourceDiscoverSchemaWriteRequestBody - to write this requested object to database.
type SourceDiscoverSchemaWriteRequestBody struct {
	// describes the available schema (catalog).
	Catalog           AirbyteCatalog `json:"catalog"`
	ConfigurationHash *string        `json:"configurationHash,omitempty"`
	ConnectorVersion  *string        `json:"connectorVersion,omitempty"`
	SourceID          *string        `json:"sourceId,omitempty"`
}

func (o *SourceDiscoverSchemaWriteRequestBody) GetCatalog() AirbyteCatalog {
	if o == nil {
		return AirbyteCatalog{}
	}
	return o.Catalog
}

func (o *SourceDiscoverSchemaWriteRequestBody) GetConfigurationHash() *string {
	if o == nil {
		return nil
	}
	return o.ConfigurationHash
}

func (o *SourceDiscoverSchemaWriteRequestBody) GetConnectorVersion() *string {
	if o == nil {
		return nil
	}
	return o.ConnectorVersion
}

func (o *SourceDiscoverSchemaWriteRequestBody) GetSourceID() *string {
	if o == nil {
		return nil
	}
	return o.SourceID
}
