// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type WebBackendWorkspaceStateResult struct {
	HasConnections  bool `json:"hasConnections"`
	HasDestinations bool `json:"hasDestinations"`
	HasSources      bool `json:"hasSources"`
}

func (o *WebBackendWorkspaceStateResult) GetHasConnections() bool {
	if o == nil {
		return false
	}
	return o.HasConnections
}

func (o *WebBackendWorkspaceStateResult) GetHasDestinations() bool {
	if o == nil {
		return false
	}
	return o.HasDestinations
}

func (o *WebBackendWorkspaceStateResult) GetHasSources() bool {
	if o == nil {
		return false
	}
	return o.HasSources
}
