// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type WorkspaceUpdateName struct {
	Name        string `json:"name"`
	WorkspaceID string `json:"workspaceId"`
}

func (o *WorkspaceUpdateName) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *WorkspaceUpdateName) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}
