// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ConnectorBuilderProjectDetailsRead struct {
	ActiveDeclarativeManifestVersion *int64  `json:"activeDeclarativeManifestVersion,omitempty"`
	BuilderProjectID                 string  `json:"builderProjectId"`
	HasDraft                         bool    `json:"hasDraft"`
	Name                             string  `json:"name"`
	SourceDefinitionID               *string `json:"sourceDefinitionId,omitempty"`
}

func (o *ConnectorBuilderProjectDetailsRead) GetActiveDeclarativeManifestVersion() *int64 {
	if o == nil {
		return nil
	}
	return o.ActiveDeclarativeManifestVersion
}

func (o *ConnectorBuilderProjectDetailsRead) GetBuilderProjectID() string {
	if o == nil {
		return ""
	}
	return o.BuilderProjectID
}

func (o *ConnectorBuilderProjectDetailsRead) GetHasDraft() bool {
	if o == nil {
		return false
	}
	return o.HasDraft
}

func (o *ConnectorBuilderProjectDetailsRead) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ConnectorBuilderProjectDetailsRead) GetSourceDefinitionID() *string {
	if o == nil {
		return nil
	}
	return o.SourceDefinitionID
}
