// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/flawless/terraform-provider-airbyte/internal/sdk/pkg/models/shared"
	"net/http"
)

type CreateConnectorBuilderProjectResponse struct {
	// Successful operation
	ConnectorBuilderProjectIDWithWorkspaceID *shared.ConnectorBuilderProjectIDWithWorkspaceID
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CreateConnectorBuilderProjectResponse) GetConnectorBuilderProjectIDWithWorkspaceID() *shared.ConnectorBuilderProjectIDWithWorkspaceID {
	if o == nil {
		return nil
	}
	return o.ConnectorBuilderProjectIDWithWorkspaceID
}

func (o *CreateConnectorBuilderProjectResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateConnectorBuilderProjectResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateConnectorBuilderProjectResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
