// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"airbyte/internal/sdk/pkg/models/shared"
	"net/http"
)

type ListDestinationDefinitionsForWorkspaceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful operation
	DestinationDefinitionReadList *shared.DestinationDefinitionReadList
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}
