// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/flawless/terraform-provider-airbyte/internal/sdk/pkg/models/shared"
	"net/http"
)

type RevokeSourceOAuthTokensResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Exception occurred; see message for details.
	KnownExceptionInfo *shared.KnownExceptionInfo
	// Object with given id was not found.
	NotFoundKnownExceptionInfo *shared.NotFoundKnownExceptionInfo
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *RevokeSourceOAuthTokensResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *RevokeSourceOAuthTokensResponse) GetKnownExceptionInfo() *shared.KnownExceptionInfo {
	if o == nil {
		return nil
	}
	return o.KnownExceptionInfo
}

func (o *RevokeSourceOAuthTokensResponse) GetNotFoundKnownExceptionInfo() *shared.NotFoundKnownExceptionInfo {
	if o == nil {
		return nil
	}
	return o.NotFoundKnownExceptionInfo
}

func (o *RevokeSourceOAuthTokensResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *RevokeSourceOAuthTokensResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
